// <auto-generated />
using angularAutoSite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace angularAutoSite.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20181119212033_myMigration")]
    partial class myMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("angularAutoSite.Models.AngAuto", b =>
                {
                    b.Property<int>("AngAuto_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("projectName");

                    b.Property<string>("thePath");

                    b.HasKey("AngAuto_ID");

                    b.ToTable("AngAutos");
                });

            modelBuilder.Entity("angularAutoSite.Models.Install", b =>
                {
                    b.Property<int>("Install_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AngAuto_ID");

                    b.Property<string>("TheInstall");

                    b.HasKey("Install_ID");

                    b.HasIndex("AngAuto_ID");

                    b.ToTable("Installs");
                });

            modelBuilder.Entity("angularAutoSite.Models.Install", b =>
                {
                    b.HasOne("angularAutoSite.Models.AngAuto", "AngAuto")
                        .WithMany()
                        .HasForeignKey("AngAuto_ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
